### ISSUE TITLE
listener receive callback ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by m-expunged** [m-expunged/guacamole-sharp#7]
Unhandled exception. System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'length')

   at System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray[T](T[] array, Range range)

   at GuacamoleSharp.Server.WebSocketHelpers.ReadFromFrames(Byte[] payload, Int32 receivedLength) in /src/GuacamoleSharp.Server/WebSocketHelpers.cs:line 70

   at GuacamoleSharp.Server.GSListener.ReceiveCallback(IAsyncResult ar) in /src/GuacamoleSharp.Server/GSListener.cs:line 261

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

--- End of stack trace from previous location ---

   at System.Threading.Tasks.AwaitTaskContinuation.RunCallback(ContextCallback callback, Object state, Task& currentTask)

--- End of stack trace from previous location ---

   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)

   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()

   at System.Threading.ThreadPoolWorkQueue.Dispatch()

   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

   at System.Threading.Thread.StartCallback()

**Comment by m-expunged** [comment]
Error while parsing broken websocket frame length?

**Comment by m-expunged** [comment]
Exception did not pop up for a while now. Might have unintentionally fixed it during refactoring...

**Comment by m-expunged** [comment]
Might be mouse cursor position desync
